---
title: "Untitled"
output: html_document
date: '2022-07-01'
---
```{r}
# load pathways
hallmark <- fgsea::gmtPathways("C:/Users/paucl/Documents/TFM/dades/collectionsets_msigdb/h.all.v7.5.1.symbols.gmt")

nice_names <- read.csv("C:/Users/paucl/Documents/TFM/dades/collectionsets_msigdb/beautiful_names.csv")
names(hallmark) <- as.vector(nice_names[,2])
```


```{r}
## FUNCTION to prepare data for run.GSEA function which requires:
  # @DEresults: toptable from Differential Expression Analysis, preferentially
              # coming from DEseq as it uses a column name "stat"
  # @gene_symbols: vector of gene symbols corresponding to rows


prepare.GSEA <- function(DEresults){
  
  if(!("stat" %in% colnames(DEresults))){print("DEresults table doesn't have a stat column")}
  
  # Select gene symbols and statistic, remove NA and if repeated compute mean
  res2 <- as.data.frame(DEresults) %>% 
    dplyr::select(symbol, stat) %>% 
    na.omit() %>% 
    distinct() %>% 
    group_by(symbol) %>% 
    summarize(stat=mean(stat))
  print("Removing NA and adjust repeateds (mean)")
  
  # Create ranks
  ranks <- tibble::deframe(res2)# converts 2xM dataframe to named vector
  print("Create ranks")
  
  # Check ranks
  barplot(sort(ranks, decreasing = T))
  print("Plotted ranks")
  
  return(ranks)
}


## FUNCTION to perform GSEA analysis which requires:
  # @title: custom name for the plot title and document name root
  # @collection_path: path to the gene set collection (.gmt extension)
  # @output_path


run.GSEA <- function(ranks, title, loaded_collection ,collection_path, output_path, width= 15, height= 10, cutoff= 0.05, save=F){
  
  # If title missing set warning and assing collection as title
  if(missing(title)){return("No title name has been provided. Collection has been set as title")}
  
  # Load library
  library(fgsea)
  print("Loaded library")
  
  # Load collection
  if(missing(loaded_collection)){
  loaded_collection <- gmtPathways(collection_path)
  print("Loaded collection")}
  
  
  # Perform GSEA 
  fgseaRes <- fgsea(pathways = loaded_collection, stats=ranks)
  print("GSEA run succesful")
  
  # Sort in descending order by NES (normalized enrichment score)
  fgseaResTidy <- fgseaRes %>%
    as_tibble() %>%
    arrange(desc(NES))
  print("tidy")

  # Create and save plot
  # p <- ggplot(fgseaResTidy, aes(reorder(pathway, NES), NES)) +
  #     geom_col(aes(fill = padj)) +
  #     coord_flip() +
  #     labs(x ="Pathway", y="Normalized Enrichment Score",
  #          title = paste0(title, " pathways NES from GSEA"))+
  #     theme_classic()
  
  p <-ggplot(fgseaResTidy[fgseaResTidy$padj<0.05,], aes(factor(reorder(pathway, NES)), NES)) +
        geom_col(aes(fill = padj)) +
        coord_flip() +
        labs(x ="", y="Normalized Enrichment Score",
             title = "")+
        theme_classic()+
        theme(legend.key.size = unit(0.2, 'in'),
              legend.position = c(0.87, 0.25),
              axis.text = element_text(face="bold"),
              axis.title = element_text(face="bold"),
              axis.line = element_line(size=0.7),
              axis.ticks = element_line(size=0.7))+
        scale_fill_gradientn(name = "FDR", 
                         trans = "log10", 
                         limits = c(min(fgseaResTidy[fgseaResTidy$padj<0.05,"padj"]), 
                                    max(fgseaResTidy[fgseaResTidy$padj<0.05,"padj"])), 
                         colours=c("#0d3c0c","#166915","#20961e","#d2ead2"))
  
  print(p)
  if(save==T){
  ggsave(output_path, p, width = width, height = height, units="in", limitsize = FALSE)
  
  print(paste0("Your plot has been saved in ", output_path))}
  return(fgseaResTidy)}

#------------------------------------------------------------------------------
##################### END OF FUNCTION DEFINITION ##############################

# FUNCTION to create a nice plot with the GSEA enrichment of a pathway with the ranked genes
plotPathwayRanks <- function(pathway, stats, gseaParam = 1, ticksSize = 0.2){
    rnk <- rank(-stats)
    ord <- order(rnk)
    statsAdj <- stats[ord]
    statsAdj <- sign(statsAdj) * (abs(statsAdj)^gseaParam)
    statsAdj <- statsAdj/max(abs(statsAdj))
    pathway <- unname(as.vector(na.omit(match(pathway, names(statsAdj)))))
    pathway <- sort(pathway)
    gseaRes <- calcGseaStat(statsAdj, selectedStats = pathway, 
                            returnAllExtremes = TRUE)
    bottoms <- gseaRes$bottoms
    tops <- gseaRes$tops
    n <- length(statsAdj)
    xs <- as.vector(rbind(pathway - 1, pathway))
    ys <- as.vector(rbind(bottoms, tops))
    toPlot <- data.frame(x = c(0, xs, n + 1), y = c(0, ys, 0))
    diff <- (max(tops) - min(bottoms))/8
    x = y = NULL
    g <- ggplot(toPlot, aes(x = x, y = y)) + 
      geom_line(color = "#20961E", 
                 size = 0.7) + 
      geom_hline(yintercept = max(tops), 
                 colour = "red", 
                 linetype = "dashed") + 
      geom_hline(yintercept = min(bottoms), 
                 theme_bw()) + 
      geom_segment(data = data.frame(x = pathway),
                   mapping = aes(x = x, 
                                 y = -diff/2, 
                                 xend = x, 
                                 yend = diff/2), 
                                 size = ticksSize) + 
      theme(panel.border = element_blank(),
            panel.grid.minor = element_blank())+
      theme_classic()+
      labs(x = "Rank",
           y = "Enrichment Score")
    print(g)}
```


```{r}
# Set contrasts
contrast.vector <- c("drug_sensitive", "drug_resistant", "resistance_control", "resistance_olaparib")
contrast_names <- c("olaparib_vs_control_allsensitive", "olaparib_vs_control_allresistant", "sensitive_vs_resistant_allcontrol", "sensitive_vs_resistant_alltreated")
names(contrast_names) <- contrast.vector

# Load DEresults
for(contrast in contrast.vector){
  assign(paste0("DEresults.", contrast),
         read.csv(paste0("C:/Users/paucl/Documents/TFM/DEA/results/",
                          contrast, "/toptable_",
                          contrast_names[contrast],".csv")))}

# GSEA workflow: gene ranking and plotting
for(contrast in contrast.vector){
  DEresults <- get(paste0("DEresults.", contrast))
  # Prepare ranks
  ranks <- prepare.GSEA(DEresults=DEresults)
  
  ## Perform GSEA analysis
  
  # Hallmark
  gsea <- run.GSEA(ranks = ranks,
           title="Hallmark",
           loaded_collection= hallmark, 
           output_path = paste0("C:/Users/paucl/Documents/TFM/DEA/results/",
                                contrast,"/", "GSEA_", contrast_names[contrast], ".png"),
           save=T,
           width= 5,
           height= 4)
  # readr::write_csv(as.data.frame(gsea),
  #                paste0("C:/Users/paucl/Documents/TFM/DEA/results/",
  #                       contrast, "/GSEAres_",
  #                       contrast_names[contrast],".csv"),
  #                col_names=T)
  }
```

```{r GSEA}
analysis_name <- "DrugEffect_onSensitive"

# Load DEresults
DEresults.drug_sensitive <- readr::read_csv("C:/Users/paucl/Documents/TFM/DEA/results/drug_sensitive/toptable_olaparib_vs_control_allsensitive.csv")

# Prepare ranks
ranksDRUG <- prepare.GSEA(DEresults=DEresults.drug_sensitive)

## Perform GSEA analysis

# Hallmark
gsea.drug_sensitive <- run.GSEA(ranks = ranksDRUG,
         title="Hallmark",
         loaded_collection= hallmark, 
         output_path = paste0("C:/Users/paucl/Documents/TFM/DEA/results/", analysis_name,"/"),
         save=F)

# Create and save plot
ggplot(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,], aes(factor(reorder(pathway, NES)), NES)) +
      geom_col(aes(fill = padj)) +
      coord_flip() +
      labs(x ="", y="Normalized Enrichment Score",
           title = "")+
      theme_classic()+
      theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))+
  scale_fill_gradientn(name = "FDR", 
                       trans = "log10", 
                       limits = c(min(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,"padj"]), 
                                  max(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,"padj"])), 
                       colours=c("#0d3c0c","#166915","#20961e","#d2ead2"))
ggsave(paste0("C:/Users/paucl/Documents/TFM/DEA/results/drug_sensitive","/", "GSEA","olaparib_vs_control_allsensitiveBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=4)


# Pathway enrichment plot with ranked genes
p1 <- plotPathwayRanks(hallmark$`Interferon Alpha Response`, ranksDRUG)



ranks <- ranksDRUG[order(ranksDRUG, decreasing = T)]

# Add color annotation and NES and FDR values
p1 + annotate("text", 
              label = paste0("NES = ", formatC(gsea.drug_sensitive$NES[grepl("Alpha", gsea.drug_sensitive$pathway)], digits=3), "\n",
                        "FDR = ", formatC(gsea.drug_sensitive$padj[grepl("Alpha", gsea.drug_sensitive$pathway)], digits=2)),
              x = 9750, y = 0.65, fontface=2)+
     annotate(
       xmin = rev(length(ranks)-ranks %>%
                cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                table() %>%
                cumsum()), 
       xmax = c(rev((length(ranks)-ranks %>%
                  cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                  table() %>%
                  cumsum()-1)[1:7]), length(ranks)),
       ymin = -0.05, ymax= 0,
       geom = "rect",
       fill = colorRampPalette(c("red","white", "blue"))(8),
       alpha = 0.65)+
  theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))
  
ggsave(paste0("C:/Users/paucl/Documents/TFM/DEA/results/drug_sensitive","/", "GSEA_alpha_ranked","olaparib_vs_control_allsensitiveBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=3)

```


#############################################################################
# ClusterProfiler enricher
#############################################################################

```{r}
# Prepare Hallmark collection as input for enricher
hall_collection <- do.call(rbind.data.frame, lapply(hallmark, data.frame))
hall_collection$term <- gsub("\\..*","",rownames(hall_collection))
colnames(hall_collection) <- c("symbol","term")
hall_collection <- cbind.data.frame(hall_collection$term, hall_collection$symbol)

for(contrast in contrast.vector){
  DEresults <- get(paste0("DEresults.", contrast))
  # Select significative genes
  degs <- subset(DEresults, c(padj<0.05 & abs(log2FoldChange)>0.585 & !is.na(symbol)))$symbol
  
  if(length(degs)<2){
    print("There are no DEGS")}
  
  else{
    print(contrast)
  # Prepare universe
  universe <- pull(DEresults[,"symbol"])
  
  # Perform enrichment
  ans <- clusterProfiler::enricher(gene = degs,
                       universe = universe,
                       TERM2GENE = hall_collection)
  
  # Plot enrichment
  p <- dotplot(ans, showCategory=10)

  print(p)}
  }
```

```{r}
# proves enrichment
mart <- biomaRt::useMart(biomart = "ENSEMBL_MART_ENSEMBL",
                         dataset = "hsapiens_gene_ensembl",
                         host = "http://www.ensembl.org")

genes <- getBM(filters = "ensembl_gene_id_version",
               attributes = c("ensembl_gene_id_version","entrezgene_id"),
               values = pull(DEresults.drug_sensitive[DEresults.drug_sensitive$padj<0.05 & 
                                                  abs(DEresults.drug_sensitive$log2FoldChange)>0.585,"ENSEMBL ID version"]), 
               mart = mart)

fgseaRes <- fgsea(pathways = hallmark, stats=ranksDRUG)
enrichplot::gseaplot2(ans.HALL.drug, geneSetID = 1, title = edo2$Description[1])

DOSE::enrichDGN(genes$entrezgene_id)

DEresults.drug_sensitiveID <- right_join(DEresults.drug_sensitive, 
                                         getBM(filters = "ensembl_gene_id_version",
               attributes = c("ensembl_gene_id_version","entrezgene_id"),
               values = pull(DEresults.drug_sensitive[,"ENSEMBL ID version"]), 
               mart = mart),
                                         by=c("ENSEMBL ID version"="ensembl_gene_id_version" ))

gsea.res <- DOSE::gseDO(tibble::deframe(as.data.frame(DEresults.drug_sensitiveID) %>% 
    dplyr::select(entrezgene_id, stat) %>% 
    na.omit() %>% 
    distinct() %>% 
    group_by(entrezgene_id) %>% 
    summarize(stat=mean(stat)) %>%
    arrange(desc(stat))))

enrichplot::gseaplot2(ans.HALL.drug, geneSetID = 1, title = "edo2$Description[1]")
```



```{r}
brcas <- list(as.vector((unlist(read.table("C:/Users/paucl/Documents/TFM/dades/collectionsets_msigdb/dna_damage_role_of_brca1_and_brca2_in_dna_repair.txt")))))

names(brcas) <- "brcas"

hallmark <- append(hallmark, brcas)

for(contrast in contrast.vector){
  print(contrast)
  DEresults <- get(paste0("DEresults.", contrast))
  # Prepare ranks
  ranks <- prepare.GSEA(DEresults=DEresults)
  
  ## Perform GSEA analysis
  
  # Hallmark
  gsea <- run.GSEA(ranks = ranks,
           title="Brcas",
           loaded_collection= hallmark, 
           output_path = paste0("C:/Users/paucl/Documents/TFM/DEA/results/",
                                contrast,"/", "GSEA_", contrast_names[contrast], ".png"),
           save=F,
           width= 5,
           height= 4)}

```



#############################################33
Codi original plots gsea



```{r GSEA}
analysis_name <- "DrugEffect_onSensitive"

# Prepare ranks
ranksDRUG <- prepare.GSEA(DEresults=DEresults.drug_sensitive)

# Perform GSEA analysis

# Hallmark
gsea.drug_sensitive <- run.GSEA(ranks = ranksDRUG,
         title="Hallmark",
         loaded_collection= hallmark, 
         output_path = paste0("C:/Users/paucl/Documents/TFM/DEA/results/", analysis_name,"/"),
         save=F)

  # Create and save plot
ggplot(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,], aes(factor(reorder(pathway, NES)), NES)) +
      geom_col(aes(fill = padj)) +
      coord_flip() +
      labs(x ="", y="Normalized Enrichment Score",
           title = "")+
      theme_classic()+
      theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))+
  #scale_x_discrete(name="",labels = factor(rev(pathnames)))+
  scale_fill_gradientn(name = "FDR", 
                       trans = "log10", 
                       limits = c(min(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,"padj"]), 
                                  max(gsea.drug_sensitive[gsea.drug_sensitive$padj<0.05,"padj"])), 
                       colours=c("#0d3c0c","#166915","#20961e","#d2ead2"))
ggsave(paste0("C:/Users/paucl/Documents/TFM/DEA/results/drug_sensitive","/", "GSEA","olaparib_vs_control_allsensitiveBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=4)

# Pathway enrichment plot with ranked genes
p1 <- plotPathwayRanks(alpha, ranksDRUG)



ranks <- ranksDRUG[order(ranksDRUG, decreasing = T)]

# Add color annotation and NES and FDR values
p1 + annotate("text", 
              label = paste0("NES = ", formatC(gsea.drug_sensitive$NES[grepl("ALPHA", gsea.drug_sensitive$pathway)], digits=3), "\n",
                        "FDR = ", formatC(gsea.drug_sensitive$padj[grepl("ALPHA", gsea.drug_sensitive$pathway)], digits=2)),
              x = 9750, y = 0.65, fontface=2)+
     annotate(
       xmin = rev(length(ranks)-ranks %>%
                cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                table() %>%
                cumsum()), 
       xmax = c(rev((length(ranks)-ranks %>%
                  cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                  table() %>%
                  cumsum()-1)[1:7]), length(ranks)),
       ymin = -0.05, ymax= 0,
       geom = "rect",
       fill = colorRampPalette(c("red","grey", "blue"))(8),
       alpha = 0.65)+
  theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))
  
ggsave(paste0("C:/Users/paucl/Documents/TFM/analysis/results/drug_sensitive","/", "GSEA_alpha_ranked","olaparib_vs_control_allsensitiveBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=3)
  
# p1 +geom_bar(data= genes, aes(x= which(names(ranks)==rownames(genes)) , y= 1, fill = cuts))+
#   ## now you can simply use one of the scale functions
#     scale_fill_brewer(palette =  "Reds")
        
# ggplot() +
#   geom_bar(data= ranks, aes(y=1, fill = cuts)) +
#   ## now you can simply use one of the scale functions
#   scale_fill_brewer(palette =  "Reds")
# 
# 
# # vector of your cuts
# my_cuts <- c(-Inf, -2, -1, -0.5, 0, 0.5, 1, 2, Inf)
# ## make a data frame and cut the ranks
# genes <-  data.frame(ranks)
# genes$cuts <- cut(genes$ranks, my_cuts)
# genes$pos <- 1:length(ranks)


#------------------------------------------------------------------------

analysis_name <- "ResistanceEffect_onTreated"

# Prepare ranks
ranksRESIST <- prepare.GSEA(DEresults=DEresults.resistance_olaparib)

# Perform GSEA analysis

# Hallmark
gsea.resistance_olaparib <- run.GSEA(ranks = ranksRESIST,
         title="Hallmark",
         collection_path= "C:/Users/paucl/Documents/TFM/dades/collectionsets_msigdb/h.all.v7.5.1.symbols.gmt", 
         output_path = paste0("C:/Users/paucl/Documents/TFM/analysis/results/", analysis_name,"/"),
         save=F)
# Create beautiful plot
pathnames2 <- c("Interferon Alpha Response", "Interferon Gamma Response", "IL6/JAK/STAT3 Signaling", "TNFa Signaling via NFkB", "Complement", "Allograft Rejection",  "Coagulation", "Inflammatory Response", "UV Response Up", "MYC Targets v1", "Glycolysis", "Hypoxia", "Cholesterol Homeostasis")

  # Create and save plot
ggplot(gsea.resistance_olaparib[gsea.resistance_olaparib$padj<0.05,], aes(factor(reorder(pathway, NES)), NES)) +
      geom_col(aes(fill = padj)) +
      coord_flip() +
      labs(x ="", y="Normalized Enrichment Score",
           title = "")+
      theme_classic()+
      theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))+
  scale_x_discrete(name="",labels = factor(rev(pathnames2)))+
  scale_fill_gradientn(name = "FDR", 
                       trans = "log10", 
                       limits = c(min(gsea.resistance_olaparib[gsea.resistance_olaparib$padj<0.05,"padj"]), 
                                  max(gsea.resistance_olaparib[gsea.resistance_olaparib$padj<0.05,"padj"])), 
                       colours=c("#0d3c0c","#166915","#20961e","#d2ead2"))
ggsave(paste0("C:/Users/paucl/Documents/TFM/analysis/results/resistance_olaparib","/", "GSEA","sensitive_vs_resistant_alltreatedBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=4)


# Pathway enrichment plot with ranked genes
p2 <- plotPathwayRanks(alpha, ranksRESIST)

ranks <- ranksRESIST[order(ranksRESIST, decreasing = T)]


# Add color annotation and NES and FDR values
p2 + annotate("text", 
              label = paste0("NES = ", formatC(gsea.resistance_olaparib$NES[grepl("ALPHA", gsea.resistance_olaparib$pathway)], digits=3), "\n",
                        "FDR = ", formatC(gsea.resistance_olaparib$padj[grepl("ALPHA", gsea.resistance_olaparib$pathway)], digits=2)),
              x = 9750, y = 0.65, fontface=2)+
     annotate(
       xmin = rev(length(ranks)-ranks %>%
                cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                table() %>%
                cumsum()), 
       xmax = c(rev((length(ranks)-ranks %>%
                  cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                  table() %>%
                  cumsum()-1)[1:7]), length(ranks)),
       ymin = -0.05, ymax= 0,
       geom = "rect",
       fill = colorRampPalette(c("red","grey", "blue"))(8),
       alpha = 0.65)+
  theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))

ggsave(paste0("C:/Users/paucl/Documents/TFM/analysis/results/resistance_olaparib","/", "GSEA_alpha_ranked","sensitive_vs_resistant_alltreatedBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=3)


# --------------------------
DEresults.drug_resistant <- readr::read_csv("C:/Users/paucl/Documents/TFM/DEA/results/drug_resistant/toptable_olaparib_vs_control_allresistant.csv")

analysis_name <- "DrugEffect_onResistant"

# Prepare ranks
ranksDRUGr <- prepare.GSEA(DEresults=DEresults.drug_resistant)

# Perform GSEA analysis

# Hallmark
gsea.drug_resistant <- run.GSEA(ranks = ranksDRUGr,
         title="Hallmark",
         loaded_collection= hallmark, 
         output_path = paste0("C:/Users/paucl/Documents/TFM/DEA/results/", analysis_name,"/"),
         save=F)

# Create beautiful plot
# pathnames <- c("Interferon Alpha Response", "Interferon Gamma Response", "TNFa Signaling via NFkB", "IL6/JAK/STAT3 Signaling", "Complement", "p53 Pathway", "Coagulation", "Protein Secretion", "Inflammatory Response", "Apoptosis", "Allograft Rejection", "UV Response Up", "Xenobiotic Metabolism", "Fatty Acid Metabolism", "MYC Targets v2", "Mitotic Spindle", "MYC Targets v1", "mTORC1 Signaling", "Glycolysis", "G2M Checkpoint", "Cholesterol Homeostasis", "Hypoxia", "E2F Targets")

  # Create and save plot
ggplot(gsea.drug_resistant[gsea.drug_resistant$padj<0.05,], aes(factor(reorder(pathway, NES)), NES)) +
      geom_col(aes(fill = padj)) +
      coord_flip() +
      labs(x ="", y="Normalized Enrichment Score",
           title = "")+
      theme_classic()+
      theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))+
  #scale_x_discrete(name="",labels = factor(rev(pathnames)))+
  scale_fill_gradientn(name = "FDR", 
                       trans = "log10", 
                       limits = c(min(gsea.drug_resistant[gsea.drug_resistant$padj<0.05,"padj"]), 
                                  max(gsea.drug_resistant[gsea.drug_resistant$padj<0.05,"padj"])), 
                       colours=c("#0d3c0c","#166915","#20961e","#d2ead2"))
ggsave(paste0("C:/Users/paucl/Documents/TFM/DEA/results/drug_resistant","/", "GSEA","olaparib_vs_control_allresistantBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=4)

# Pathway enrichment plot with ranked genes
p1 <- plotPathwayRanks(alpha, ranksDRUGr)



ranks <- ranksDRUGr[order(ranksDRUGr, decreasing = T)]

# Add color annotation and NES and FDR values
p1 + annotate("text", 
              label = paste0("NES = ", formatC(gsea.drug_resistant$NES[grepl("ALPHA", gsea.drug_resistant$pathway)], digits=3), "\n",
                        "FDR = ", formatC(gsea.drug_resistant$padj[grepl("ALPHA", gsea.drug_resistant$pathway)], digits=2)),
              x = 9750, y = 0.65, fontface=2)+
     annotate(
       xmin = rev(length(ranks)-ranks %>%
                cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                table() %>%
                cumsum()), 
       xmax = c(rev((length(ranks)-ranks %>%
                  cut(c(Inf, 2, 1, 0.5, 0, -0.5, -1, -2, -Inf)) %>%
                  table() %>%
                  cumsum()-1)[1:7]), length(ranks)),
       ymin = -0.05, ymax= 0,
       geom = "rect",
       fill = colorRampPalette(c("red","grey", "blue"))(8),
       alpha = 0.65)+
  theme(legend.key.size = unit(0.2, 'in'),
            legend.position = c(0.87, 0.25),
            axis.text = element_text(face="bold"),
            axis.title = element_text(face="bold"),
            axis.line = element_line(size=0.7),
            axis.ticks = element_line(size=0.7))
  
ggsave(paste0("C:/Users/paucl/Documents/TFM/analysis/results/drug_sensitive","/", "GSEA_alpha_ranked","olaparib_vs_control_allsensitiveBOLD" ,".png"), units="in", limitsize = FALSE, width=5, height=3)

```

